const state={region:"all",category:"all",q:"",minImportance:0,meta:{regions:{},categories:{},refresh_interval_seconds:600}};
const $=(id)=>document.getElementById(id);
function fmtTime(iso){if(!iso)return"-";try{const d=new Date(iso),now=new Date(),diff=(now-d)/1000;if(diff<60)return`${Math.floor(diff)}s ago`;if(diff<3600)return`${Math.floor(diff/60)}m ago`;if(diff<86400)return`${Math.floor(diff/3600)}h ago`;return d.toISOString().slice(0,16).replace("T"," ");}catch{return iso;}}
function importanceClass(s){if(s>=6)return"crit";if(s>=3)return"warn";if(s>=1)return"norm";return"";}
function esc(s){return(s||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
function buildChips(cid,key,opts,all=true){const c=$(cid);c.querySelectorAll(".chip").forEach(e=>e.remove());const o=all?{all:"All",...opts}:opts;Object.entries(o).forEach(([k,label])=>{const b=document.createElement("button");b.className="chip";b.dataset.value=k;b.textContent=label;if(state[key]===k)b.classList.add("active");b.addEventListener("click",()=>{state[key]=k;c.querySelectorAll(".chip").forEach(e=>e.classList.toggle("active",e.dataset.value===k));loadEvents();});c.appendChild(b);});}
async function fetchJSON(url,opts){const r=await fetch(url,opts);if(!r.ok)throw new Error(`${r.status}`);return r.json();}
async function loadMeta(){const m=await fetchJSON("/api/meta");state.meta=m;buildChips("region-filters","region",m.regions);buildChips("category-filters","category",m.categories);}
async function loadStats(){try{const s=await fetchJSON("/api/stats");$("stat-total").textContent=s.total??0;$("stat-mil").textContent=s.by_category?.military??0;$("stat-pol").textContent=s.by_category?.politics??0;$("stat-cyb").textContent=s.by_category?.cyber??0;const bars=$("region-bars");bars.innerHTML="";const rmap=state.meta.regions||{};const items=Object.entries(rmap).map(([k,n])=>[k,n,s.by_region?.[k]??0]).sort((a,b)=>b[2]-a[2]);const maxv=Math.max(1,...items.map(x=>x[2]));items.forEach(([_,name,n])=>{const row=document.createElement("div");row.className="bar-row";row.innerHTML=`<span class="name">${name}</span><span class="bar"><span style="width:${(n/maxv)*100}%"></span></span><span class="val">${n}</span>`;bars.appendChild(row);});}catch(e){console.warn(e);}}
async function loadSources(){try{const{sources}=await fetchJSON("/api/sources");const ul=$("sources");ul.innerHTML="";if(!sources?.length){ul.innerHTML='<li><span class="s-name" style="color:var(--muted)">(not fetched yet)</span></li>';return;}sources.sort((a,b)=>(b.last_fetched_at||"").localeCompare(a.last_fetched_at||"")).forEach(s=>{const li=document.createElement("li");const cls=s.last_status==="ok"?"ok":"error";li.innerHTML=`<span class="s-status ${cls}"></span><span class="s-name">${esc(s.name)}</span><span class="s-count">${s.item_count??0}</span>`;if(s.last_error)li.title=s.last_error;ul.appendChild(li);});}catch(e){console.warn(e);}}
async function loadEvents(){const p=new URLSearchParams();if(state.region!=="all")p.set("region",state.region);if(state.category!=="all")p.set("category",state.category);if(state.q)p.set("q",state.q);if(state.minImportance>0)p.set("min_importance",state.minImportance);p.set("limit","300");try{const{events}=await fetchJSON("/api/events?"+p);renderEvents(events||[]);$("feed-meta").textContent=`${events.length} events`;}catch(e){console.warn(e);$("feed-meta").textContent="error";}}
function renderEvents(events){const ul=$("events");ul.innerHTML="";$("empty-state").hidden=events.length>0;for(const ev of events){const li=document.createElement("li");li.className=`event ${importanceClass(ev.importance)}`;const tags=(ev.categories||[]).map(c=>`<span class="tag">${esc(c)}</span>`).join("");const region=ev.region&&ev.region!=="global"?`<span class="tag region">${esc(state.meta.regions[ev.region]||ev.region)}</span>`:"";
li.innerHTML=`<div class="top"><span class="src">${esc(ev.source)}</span><span>${fmtTime(ev.published_at||ev.fetched_at)}<span class="imp">${ev.importance?.toFixed(1)??"0.0"}</span></span></div><div class="title-line"><a href="${esc(ev.url)}" target="_blank" rel="noopener">${esc(ev.title)}</a></div>${ev.summary?`<div class="summary">${esc(ev.summary)}</div>`:""}<div class="tags">${region}${tags}</div>`;ul.appendChild(li);}}
let st=null;
$("search").addEventListener("input",e=>{clearTimeout(st);st=setTimeout(()=>{state.q=e.target.value.trim();loadEvents();},250);});
$("importance").addEventListener("input",e=>{state.minImportance=parseFloat(e.target.value);$("importance-val").textContent=state.minImportance.toFixed(1)+"+";});
$("importance").addEventListener("change",()=>loadEvents());
$("refresh").addEventListener("click",async()=>{const btn=$("refresh");btn.disabled=true;btn.textContent="... refreshing";try{await fetch("/api/refresh",{method:"POST"});await Promise.all([loadEvents(),loadStats(),loadSources()]);$("last-update").textContent="Updated "+new Date().toISOString().slice(11,19)+" UTC";}catch(e){console.warn(e);}finally{btn.disabled=false;btn.textContent="↻ Refresh";}});
async function boot(){await loadMeta();await Promise.all([loadEvents(),loadStats(),loadSources()]);$("last-update").textContent="Updated "+new Date().toISOString().slice(11,19)+" UTC";setInterval(async()=>{await Promise.all([loadEvents(),loadStats(),loadSources()]);$("last-update").textContent="Updated "+new Date().toISOString().slice(11,19)+" UTC";},60000);}
boot();
